### ISSUE TITLE
Provide a CRUD example

### ISSUE THREAD

**Issue by amirm-eng** [rmuif/web#420]
I apologize if my question is such a basic question but unfortunately I was not able to find an answer to my question here.

I have successfully run the app and connected it to my Firebase account.
Now i need to create a new data model let's say named "todoitem" and generate a new page and be able to do CRUD in that page for the todoitem.

In other words:
 -  if I GET at /todoitem I should be able to get all the todoitem that the user is an author of
 - if I POST to /todoitem/new I will be adding a new todoitem
 - if IPUT by ID at /todoitem/:id/edit
 - if I DELETE at /todoitem/:id . I should be able to delete that todoitem

I basically need some guidance in two areas:
 1) How can I create a new page and add routes (/todoitem) to that page 
 2) How to go about adding a new data model and doing a restful CRUD?

Any help, pointers etc would be much appreciated,
Thanks

**Comment by phoqe** [comment]
Hello @amirm-eng and welcome to GitHub!

The answer to your first question can be divided into some steps (assume the page is called "Room"):
1. Create a `RoomContent` folder along with `RoomContent.js`, `RoomContent.test.js`, and `index.js`.
2. Initialize a new React component in `RoomContent.js`.
3. Add a basic smoke test for `RoomContent.test.js`, you can find pretty much any component and copy-paste their test and modifying it for `RoomContent`.
4. Add `export { default } from "./RoomContent";` in `index.js`. This is used to more easily reference the component from other components.
5. Add `<Route path="/room/:roomId"><RoomContent /></Route>`, for example,  in `Router.js` under the already defined routes.
6. Navigate to http://localhost:3000/room/test and you’ll be on your new page.

The setup of a back-end RESTful API compatible with RMUIF might be cumbersome, I have not tried it yet, quite frankly not with a lot of React projects. I would suggest consulting https://create-react-app.dev/docs/integrating-with-an-api-backend for more information on how to do so. RMUIF is based on CRA, so the principle is the same, I would imagine. Other than that, you would do your API calls in `componentDidMount` on your pages using `fetch()` or axios.

Some additional resources:
https://create-react-app.dev/docs/documentation-intro
https://reacttraining.com/react-router/web/guides/quick-start
https://expressjs.com/
https://www.freecodecamp.org/news/create-a-react-frontend-a-node-express-backend-and-connect-them-together-c5798926047c/

Thank you for using RMUIF and have a pleasant evening.

**Comment by amirm-eng** [comment]
Thank you so much for your help @phoqe 
I really appreciate your step by step and clear explanations, it helped me alot. 

Q 1) So I was able to follow your instructions regarding my first question and it worked for me. Thank you.

Q 2) In regards to the second question, I meant to say how can I do CRUD with the recommended way that this project talks to the Firebase Firestore?

In other words, for instance let's say we have created a brand new page using your instructions in step 1 and this page is now is located at /room/:roomId 
Now let's say we have created a data object called roomdata in Firestore.

A roomdata object in Firestore would look like this:

roomdata: {
    name: 'some room name',
    category: 'social',
    capacity: 200
}

To get all the roomdata objects for the currently logged in user, what's the best way that I can import the same instance of the `firestore` that is used in App.js into `RoomContent.js` and have access to the user Id of the user that is logged in and consequently be able to do queries like:  

`firestore.collection("roomdata").get().then(function(querySnapshot) {...}`

It would be great if you could help me see some basic implementation that I should have in the `RoomContent.js` that will allow me to fetch all roomdata and user objects. 

Thank you :)

**Comment by phoqe** [comment]
You can accomplish this by using the [`useParams()`](https://reacttraining.com/react-router/web/example/url-params) hook from React Router in conjunction with Firebase Cloud Firestore.

It would look something like this:

```js
import React, { useState, useEffect } from "react";
import { useParams } from "react-router-dom";

import { firestore } from "../../firebase";

function RoomContent() {
  const [room, setRoom] = useState(null);
  const { roomId } = useParams();

  useEffect(() => {
    firestore.collection("rooms").doc(roomId).get().then((value) => {
      setRoom(value.data());
    }).catch((reason) => {
      console.error(reason);
    });
  });

  if (!room) {
    return null;
  }

  return (
    <div>
      {room.name}
    </div>
  );
}

export default RoomContent;
```

**Comment by phoqe** [comment]
Also, regarding extending Webpack, you need to eject CRA by using `npm run eject` or `yarn eject`, read [this](https://create-react-app.dev/docs/available-scripts#npm-run-eject) before doing it because it’s a one-way operation.

**Comment by phoqe** [comment]
I think I will take your request one step further and begin working on the user pages, I just need to solve for the user data consistency first, meaning I can guarantee that users have some form of info available before showing a profile. I will do a route at `/user/:userId` which will require the user to be authenticated. And since this is the first user-to-user interaction, I will implement some administrative actions for the user as well (for users that are administrators of course) and begin thinking of how to do relationships with users etc.

**Comment by amirm-eng** [comment]
- Thank you for the sample code, I'm yet to try that. I'll report here once I try it.
- About ejecting the CRA to be able to extend Webpack, to be honest I feel uncomfortable to eject CRA as by doing so my project becomes out of sync with rmuif. I may have to look for alternative approaches to load an external html template into my react component. I'll look into it. Thanks.

**Comment by ortegoncarlos** [comment]
Thanks, thats pretty helpful, i think you should add a crud example to de documentation, I now we can figure it out learning deeper firebase, react and redux, but is really nice to understand it from your point of view.

**Comment by amirm-eng** [comment]
In regards to building on top of this request, I think that's a great idea and the whole community can benefit from it.

User Profile:
------------
Having a dedicated profile page for the user is a necessity for almost any SaaS app.

CRUD
------
Additionally a sample CRUD page which can easily be extended would be a great starting point for anyone to custom build their own model for the crud operations.

I would suggest we name the data model an "article":

All of the following would work based on user permissions and user role:

POST /article/new
GET all articles  /article/
GET single article. /article/:id
PUT update an article. /article/:id
DELETE remove an article. /article/:id

What are your thoughts @phoqe 
Thank you

**Comment by phoqe** [comment]
Yes, I agree with your proposal. I will start with the profiles after I’ve fixed the issue with user data consistency and then move on to the actual content.

Thank you for your feedback!

**Comment by amirm-eng** [comment]
This is great news.
Looking forward to it..
Please let me know if I can help with any brainstorming or really anything at all,
Best,

**Comment by phoqe** [comment]
By the way, @amirm-eng, do not use that code snippet for content fetching, you should use something similar to:

```js
  useEffect(() => {
    return firestore
      .collection("users")
      .doc(userId)
      .onSnapshot(
        snapshot => {
          setUser(snapshot.data());
          setLoading(false);
        },
        error => {
          setError(error);
        }
      );
  }, [userId]);
```

Really important to include the [userId] part in the end, else it will just continue to register listeners all the time.

**Comment by phoqe** [comment]
Here's a more complete example, including error handling:
```js
import React, { useState, useEffect } from "react";

import { useParams } from "react-router-dom";

import { firestore } from "../../firebase";

import ErrorIcon from "@material-ui/icons/Error";
import PersonOutlineIcon from "@material-ui/icons/PersonOutline";

import EmptyState from "../EmptyState";

function UserContent() {
  const [loading, setLoading] = useState(true);
  const [user, setUser] = useState(null);
  const [error, setError] = useState(null);
  const { userId } = useParams();

  useEffect(() => {
    return firestore
      .collection("users")
      .doc(userId)
      .onSnapshot(
        snapshot => {
          setUser(snapshot.data());
          setLoading(false);
        },
        error => {
          setError(error);
        }
      );
  }, [userId]);

  if (error) {
    return (
      <EmptyState
        icon={<ErrorIcon />}
        title="Something went wrong"
        description="There was an error while trying to fetch the requested user"
      />
    );
  }

  if (loading) {
    return null;
  }

  if (!user) {
    return (
      <EmptyState
        icon={<PersonOutlineIcon />}
        title="User not found"
        description="The requested user was not found"
      />
    );
  }

  return <EmptyState title={user.username} />;
}

export default UserContent;
```

**Comment by phoqe** [comment]
@amirm-eng @ortegoncarlos There’s now a `user-content` branched of `develop`, it’s only basic info at this point, but I will continue when time allows.

**Comment by amirm-eng** [comment]
I was just about to get started with the code that you provided for `UserContent` that I saw your post that you already have the  `user-content` done.  Perfect 💯 

So what are the user facing changes?

**Comment by phoqe** [comment]
Yes, I am having some trouble with merging CI to GitHub Actions at the moment but that’s the plan. I am working on a v3.0 release and am merging documentation over to GitBooks, previewable at https://phoqe.gitbook.io/rmuif at the moment (will be docs.rmuif.com when done).

**Comment by amirm-eng** [comment]
https://docs.rmuif.com/ is great and well organized.

Just one question though, should the docs mention anything about user `role` and perhaps the `admin` role as well?

**Comment by phoqe** [comment]
I am currently adding more advanced sections as well.

**Comment by phoqe** [comment]
@amirm-eng There’s now an initial draft on https://docs.rmuif.com/maintenance/roles

**Comment by phoqe** [comment]
Tell me if there’s something missing and I’ll add it.

**Comment by amirm-eng** [comment]
@phoqe 
Looks great, it includes pages, roles and updates which are the main sections needed.

One thing that came to mind when reading the 'Set Role for User' section was how do I know that I can not  be hacked since anyone can intercept the running code in the browser to change a role of the logged in user.
Obviously this has been addressed by Firebase (I think by using privileged environments) but just thought it would be worth mentioning it in your documentation or simply by adding a link to where people can read about it.

https://docs.rmuif.com/maintenance/roles#set-role-for-user

**Comment by phoqe** [comment]
@amirm-eng Thank you for your feedback, I have added some new explanations in those sections and hope they are adequate.

**Comment by amirm-eng** [comment]
@phoqe I agree, it's great and covers all those areas. thnx

**Comment by phoqe** [comment]
@amirm-eng You’re welcome. I will soon also have a main site up at https://rmuif.com and will move the demo to https://demo.rmuif.com, I will keep this issue open until I’ve added the article example to the main app and merged it to `master`.

**Comment by amirm-eng** [comment]
@phoqe 
That's great, thank you for letting me know, looking forward to the article example... . 💯 👍

**Comment by amirm-eng** [comment]
Hi @phoqe 
I noticed the new homepage for the project that you have built. It's looking very sleek and nice. 

If I may suggest, the acronym "CRA" for Create React App is commonly used across the industry but I can imaging many people still not knowing that acronym.

It would be great to actually put that in bracket for them to know. ie. "CRA (Create React App)"
It would help with the SEO also, hopefully the project can be found by people much easier when they search in google.

I apologize if I am suggesting something that is irrelevant.

**Comment by phoqe** [comment]
Thank you for your feedback @amirm-eng, yes, I agree with you and will probably rewrite some sections but am currently awaiting a response from the CRA team regarding usage with their logo etc.

Your advice is good, thank you :)

**Comment by amirm-eng** [comment]
Hi @phoqe 

I was thinking more about how the work for the "article" CRUD can become more generic so that anyone adopting this project would be able to leverage the crud operation capabilities in a boarder form as it is commonly seen in SaaS applications these days.

So then I came up with a list of about 7 important concepts that are used in SaaS and/or Social applications. But then later I thought to myself that this list should get even more shrunken down to 2 items that are super essential in many applications.
So this is the 2 items that I think are essential to many SaaS web apps.

1) Role based CRUD and views 
2) Payment Subscriptions


1: The CRUD capability as we discussed previously would for instance consist of the following:  
 - a no role (authenticated) user as well as premium or admin user would be able to view all articles posted by a premium role user. All articles can be viewed at (/article/)       
         - Note: For listing all articles anyone has posted, no pagination or lazy loading would be necessary initially as it just adds to the work. It can be added at a later time.        
 - all articles that are posted by a specific premium user can be viewed at (/article/:userId)   
 - when a user clicks on any of the articles title, that user is taken to a dedicated page for that article located at /article/:id where in which page all details of that article are shown    
 - an article can be POSTed (/article/new) only and only by a user who has one of these roles ["premium", "admin"].   
 - articles can be UPDATed or DELETEd by the same premium user or any admin user.


2: many applications have premium based offerings/services. Let's think of a premium service in our case to be the ability to post an article.
   - Users who are authenticated but still don't have a premium or admin role, can become a premium role user by subscribing to a subscription plan.   
 - Let's call this subscription plan: "paidSubscriptionPlan"  
 - To become a premium user the user would be taken to a page at (/upgrade/) where the user will see a form that includes their personal and credit card info and the amount for the premium subscription ie. $1 / month    
 - Note: this can be a Stripe integration. Stripe has a Firebase integration:
     https://firebase.google.com/docs/use-cases/payments
     https://github.com/firebase/functions-samples/tree/master/stripe  
 - Upon completion a callback would be called on Firebase side to update user role to premium.  
     - Note: No need to have an administration page for cancellation or subscription etc. People can extend those additional functionalities on their own or they can be added in the future.


Sorry if I talked alot, these were my thoughts. 
@phoqe can't wait to know what you think...?

Thanks,
Best,

**Comment by phoqe** [comment]
I have actually considered your points before, especially payments through Stripe. It is a neat feature to have and makes the app more distinctive as there are not a lot of starter projects featuring a payment integration.

The first option is relatively easy to implement, the logic is essentially already implemented. I think I will have to postpone a Stripe integration until I’ve resolved some more issues and making the overall project more stable.

Thank you for your thoughts, it’s great to hear feedback on this level.

**Comment by amirm-eng** [comment]
It's great to hear that you have considered both of the especially the payments through Stripe. The project will be very useful and likely attract alot of attention in the CRA and Firebase community.

Btw, in terms of the first option, in which branch will it be included, `develop` or it will have its own dedicated branch?

Thank you @phoqe

**Comment by phoqe** [comment]
@amirm-eng It will be on its separate branch, branched off `develop`. Once it’s started I don’t think it’ll take a long time to complete though.

**Comment by amirm-eng** [comment]
@phoqe cool, thanks

**Comment by amirm-eng** [comment]
Great call on changing the title, our thoughts evolved alot through our discussions.

Btw out of curiosity, what are your plans in terms of the timeline you think you could work on this?
Thanks alot

**Comment by phoqe** [comment]
Hello again, I have to complete #461 first, I will add this to the [Roadmap](https://docs.rmuif.com/docs/roadmap), ETA is unknown at the moment.

**Comment by amirm-eng** [comment]
Awesome, thanks for the update. Really hope that this could be included in
the current version / v3 Roadmap. This will give a good edge to the product.
Stability i great but people will be very pleased with features like CRUD
and Payment/Subscription.
Thanks, cheers

**Comment by phoqe** [comment]
I recognize the need for this feature, I advice users of this template to study the user profiles at this time. And to clarify, the order of the items in the roadmap is not based on priority, it will be done in the order I see fit but am unable to sort them at the moment due to the more pressing issue, #461.

**Comment by amirm-eng** [comment]
Understood, thank you for the clarification.
