### ISSUE TITLE
Adopt monorepo structure

### ISSUE THREAD

**Issue by phoqe** [rmuif/web#461]
We should let the users decide which code style they want. Prettier could be fine for actual development of RMUIF but not shipping with it. It might be a good idea to move completely to using Create React App templates instead of the user cloning the whole repo. Any thoughts?

**Comment by nainardev** [comment]
Use Prettier. Benifits in the long run

**Comment by phoqe** [comment]
We could enforce Prettier by default, but everyone doesn’t have the editor integration for it and will probably be clueless on how to continue when the app refuses to build due to a style issue. There could be a section in the documentation for it or we could add a setup tool that changes the code style for the project.

**Comment by nainardev** [comment]
Also, when converting class components into functional, PropTypes are valid?

**Comment by nainardev** [comment]
I completed converting Dialog comp

**Comment by phoqe** [comment]
Yes, PropTypes work for all components with props. Please keep the discussion in this issue on topic though.

**Comment by phoqe** [comment]
Also, add support for [`yarn create`](https://classic.yarnpkg.com/en/docs/cli/create).

**Comment by nainardev** [comment]
`yarn create` then?

**Comment by phoqe** [comment]
@nainardev What do you mean? It's essentially just a shortcut for `npx create-react-app`. Instead, you would write `yarn create react-app my-app --template rmuif`.

**Comment by nainardev** [comment]
Oh, I didn't knew it. Thanks. So this will be available *only* as a CRA template?

**Comment by phoqe** [comment]
Yes, *only* as a CRA template. This repo will adopt a monorepo structure, including the docs into this one instead of a separate repo.

**Comment by nainardev** [comment]
Is docs updated to inform users?

**Comment by phoqe** [comment]
No, it might be good advice to tell users to wait. I will update the docs.

**Comment by phoqe** [comment]
@nainardev How's this?
![image](https://user-images.githubusercontent.com/7033377/75880225-2e2d3a80-5e1d-11ea-92e2-db7b808f3e82.png)

**Comment by nainardev** [comment]
Don't use red color though, try orange or blue

**Comment by phoqe** [comment]
There's been a change of plans, the repo will not be monorepo. The template will move to cra-template-rmuif though and that process is ongoing.

**Comment by nainardev** [comment]
fortsätt på rätt väg Lånberg

**Comment by phoqe** [comment]
Hahaha tack!
