### ISSUE TITLE
Integrate with Netlify

### ISSUE THREAD

**Issue by phoqe** [rmuif/web#473]

**Comment by tchalvak** [comment]
Just a note that your README demo site no longer provides a preview and instead just errors:

https://demo.rmuif.com/

![2C010511-321F-463F-AAE4-B4530E61E135](https://user-images.githubusercontent.com/23353/76701057-e5367b00-6693-11ea-9e50-b120f6093953.png)

**Comment by phoqe** [comment]
Yes, thank you for noticing. We are aware of this problem are working on getting a demo site up and running ASAP.

**Comment by phoqe** [comment]
#513
