### ISSUE TITLE
Notify users when site is cached for offline-use

### ISSUE THREAD

**Issue by nainardev** [rmuif/web#482]
## Problem

Service Workers are yet to be fully understood by new users and problems might arise. Notifying them is a good idea, that way the user knows they’re safe when offline.

## Solution

Add some form of indication that the app is ready to be used offline.

## Alternatives

N/A

## Additional context

https://github.com/facebook/create-react-app/issues/2398#issuecomment-304700498

**Comment by phoqe** [comment]
Yes, I agree.
