### ISSUE TITLE
Switch to other provider for project sites (main, demo, docs)

### ISSUE THREAD

**Issue by phoqe** [rmuif/web#483]
## Problem

Netlify is less problematic to work with than GitHub Pages, will be less of a hassle to integrate with CI/CD flows.

## Solution

Switch to Netlify for demo.rmuif.com

## Alternatives

GitHub Pages (currently in use)
Firebase Hosting
Heroku
ZEIT Now

## Additional context

N/A

**Comment by nainardev** [comment]
Now is better

**Comment by phoqe** [comment]
It looks awesome, I will investigate the differences more. Thank you for the suggestion :)

**Comment by nainardev** [comment]
close this issue??

**Comment by phoqe** [comment]
I still have to do some setup for this repo.
