### ISSUE TITLE
Gain more publicity for the project

### ISSUE THREAD

**Issue by nainardev** [rmuif/web#484]
Add this to Milestone

## Problem

Engagement is low in the project. RMUIF should be easily discoverable

## Solution

Promotion of the project in r/reactjs, r/javascript, r/webdev, and in Hacker News, et cetra

**Comment by phoqe** [comment]
I like this suggestion but I want the project to mature a bit more and be more welcome for contributors as well as refine existing features and complete the Hooks conversion.

**Comment by phoqe** [comment]
@nainardev What do you think needs to be added to welcome more contributors? A CONTRIBUTING.md and PULL_REQUEST_TEMPLATE.md file?

**Comment by nainardev** [comment]
Those are secondary. First we need people to just discover the project. If they like it they would contribute slowly(like bug, issues) until they become contributors

**Comment by phoqe** [comment]
Yeah, but would be good to have those in place when people come here. I will create an issue.
