### ISSUE TITLE
New branch

### ISSUE THREAD

**Issue by nainardev** [rmuif/web#488]
can you merge my PRs #467 to #470  into new branch called functional components or something?

**Comment by phoqe** [comment]
Can you begin a new branch called `hooks-conversion`? 😅

**Comment by nainardev** [comment]
I don't have write acces to this repo. You do. So you can create one

**Comment by nainardev** [comment]
Just asking as you haven't responded about PRs

**Comment by phoqe** [comment]
I will take your commits into a branch, sorry for the delay.
