### ISSUE TITLE
Move from **Class** component to **Functional** component

### ISSUE THREAD

**Issue by Prottoy2938** [rmuif/web#530]
## Code Style

Right now this project uses react **Class** components, I suggest we should convert our components to **functional** components.

## Benefits

> 1. Code will be a lot shorter and easier to understand.

## Demerits 

> 1. As most online React courses on starts with **Class** based components, new learners on React might have troubles understanding **Functional** components.

**Comment by phoqe** [comment]
We are gradually moving to functional components and more specifically Hooks, it’s on the [roadmap](https://docs.rmuif.com/roadmap#conversion-to-hooks).
