### ISSUE TITLE
usesEffect hook that doesn't run on initial render

### ISSUE THREAD

**Issue by Prottoy2938** [rmuif/web#537]
## Available snippet

Is there are any `useEffect` hook created on the project that doesn't run on initial render? I need to convert a React class component to a Functional component. If there's not, I would have to implement one.

**Comment by phoqe** [comment]
Could you please elaborate?

**Comment by phoqe** [comment]
Closing this, if you still have any questions feel free to join us on Discord.

**Comment by Prottoy2938** [comment]
When trying to convert **Class** component to **Functional** component, it often needs to use `useEffect` to create a `callBack` function after setting the state. To do that, we need a `useEffect` which doesn't run on initial render. Since we use `callBack` functions after `setState` quite a lot, I think it would be better if we have a custom hook for it created in a new file. Thus, if we need to use a `useEffect hook` like that, we can just import that file. 

Heres a Stackoverflow post on it: https://stackoverflow.com/a/57941438/12200634

**Comment by phoqe** [comment]
Alright, I get what you mean, but I don't think we're there yet. It might get added when we are supporting Hooks ultimately.
