### ISSUE TITLE
users list error

### ISSUE THREAD

**Issue by amirm-eng** [rmuif/web#539]
Hope all is well and staying safe and practicing social distancing,

I was wondering if I can bother you with a question,
I just did a brand new install and the app seems to be working fine but I'm having some trouble with the firebase admin tools.
Firstly, I had to do manual installation of the following as it seems that they were not pre-installed as a part of the app's installation:
npm install firebase-admin
npm install cli-table

Then after **cd /tools**
I'm getting the following error after running any of the user related commands.
I was wondering if I could get some help from you.

Thank you :)

`0L7HV2J:tools axm$ **npm run users list**

> tools@0.1.0 users /Users/axm/my-app/tools
> node users "list"

**Failed to determine project ID: Error while making request: getaddrinfo ENOTFOUND metadata.google.internal. Error code: ENOTFOUND**
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tools@0.1.0 users: `node users "list"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tools@0.1.0 users script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?`

**Comment by phoqe** [comment]
Hello Amir, here's a quickstart for the tools directory:

```sh
cd tools
yarn
```

And for the error you're getting:

> Set the environment variable GOOGLE_APPLICATION_CREDENTIALS to the file path of the JSON file that contains your service account key. This variable only applies to your current shell session, so if you open a new session, set the variable again.

For example:

```sh
export GOOGLE_APPLICATION_CREDENTIALS="/home/user/Downloads/service-account-file.json"
```

You can read more about it [here](https://firebase.google.com/docs/admin/setup).

Apologies for any inconvenience, the tools will move to a separate repo and module that will be accessible from anywhere. It is not done yet but will be available [here](https://github.com/rmuif/cli).

**Comment by phoqe** [comment]
Closing this issue, if you have any more problems feel free to reopen.
