### ISSUE TITLE
Refactor README

### ISSUE THREAD

**Issue by nainardev** [rmuif/web#547]
## Problem

Readme here is good but could be better and consise
Could have a gif, centered logo, etc
## Solution

Refactor Readme

[matiassingers/awesome-readme](https://github.com/matiassingers/awesome-readme/blob/master/readme.md) contains some awesome examples

Readme of [amitmerchant1990/electron-markdownify](https://github.com/amitmerchant1990/electron-markdownify/blob/master/README.md) is what I recommend our project can adopt

Waiting for your feedback

**Comment by phoqe** [comment]
@nainardev What about [this](https://github.com/rmuif/web/blob/dev/README.md)?

**Comment by nainardev** [comment]
1st paragraph could be shortened to be concise, or a tagline could replace 1st paragraph
