### ISSUE TITLE
Support scopes

### ISSUE THREAD

**Issue by tugal** [rmuif/web#562]
## Problem

Hi, working on a github integration app, i need to provide "scope" [https://developer.github.com/apps/building-oauth-apps/understanding-scopes-for-oauth-apps/](https://developer.github.com/apps/building-oauth-apps/understanding-scopes-for-oauth-apps/)

## Solution

in AuthProviders

```json
{
    providerId: "github.com",
    color: "#24292e",
    icon: <GitHubCircleIcon />,
    name: "GitHub",
    scope: "public_repo"
  },
```

in Authentification

```js
provider.addScope(scope);
```

## Additional context

**Comment by phoqe** [comment]
@tugal Thanks for your issue, I am looking into it. Do you know if the `addScope` method supports adding multiple scopes in the same call or do I need to call `addScope` for every scope I want to add?

**Comment by phoqe** [comment]
https://github.com/rmuif/web/pull/571
