### ISSUE TITLE
Enable only providers you need

### ISSUE THREAD

**Issue by tugal** [rmuif/web#563]
## Problem

Hi, working on a github integration app, i want only my users to connect with Github.

## Solution

in AuthProviders

```json
{
    providerId: "github.com",
    color: "#24292e",
    icon: <GitHubCircleIcon />,
    name: "GitHub",

    active: true,
  },
```
## Additional context

**Comment by phoqe** [comment]
You can just remove the providers you don't want from `authProviders.js`.
