### ISSUE TITLE
Attempted import error: 'FacebookBox' is not exported from 'mdi-material-ui' (imported as 'FacebookBoxIcon')

### ISSUE THREAD

**Issue by zaabalonso** [rmuif/web#565]
## Description

Both build and start are failing with import errors in authProviders.js

## Reproduction

npx create-react-app rendezvous --template rmuif
yarn start or yarn build
start/build failed to compile.

> yarn run v1.22.4
> $ react-scripts build
> Creating an optimized production build...
> Failed to compile.
> 
> ./src/authProviders.js
> Attempted import error: 'FacebookBox' is not exported from 'mdi-material-ui' (imported as 'FacebookBoxIcon').
> 
> 
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> 

## Expected behavior

start/build are starting/building 

## Screenshots

![Screen Shot 2020-04-19 at 22 25 08](https://user-images.githubusercontent.com/1202016/79716929-fe32dd00-828c-11ea-9d71-9c02c811d456.png)

## Desktop

- OS: MacOS Catalina
- Version: 10.15.4

**Comment by phoqe** [comment]
This is fixed in `dev`, just haven't released it yet. Update the imports of `authProviders.js` to match:

```js
import React from "react";

import { Apple as AppleIcon } from "mdi-material-ui";
import { Facebook as FacebookIcon } from "mdi-material-ui";
import { Github as GitHubIcon } from "mdi-material-ui";
import { Google as GoogleIcon } from "mdi-material-ui";
import { Microsoft as MicrosoftIcon } from "mdi-material-ui";
import { Twitter as TwitterIcon } from "mdi-material-ui";
import { Yahoo as YahooIcon } from "mdi-material-ui";
```

**Comment by zaabalonso** [comment]
@phoqe  ;) thanks didn't see that.

prepared a PR against master in case you wanna merge it.

https://github.com/rmuif/web/pull/566

**Comment by phoqe** [comment]
Thank you @zaabalonso! Seeing as it's already fixed in `dev` I will close it. Should you create more PRs, please target `dev`, thank you 😄
