### ISSUE TITLE
No start script

### ISSUE THREAD

**Issue by MincePie** [rmuif/web#624]
## Description

Hey - everyone has clearly figured this out - but I cant get this code to run. 

There is no start script in your package.json - is it somewhere esle? Have I missed some getting started instructions?  Thank you!

**Comment by MincePie** [comment]
i reran the install - something made it skip. thanks anyway.

**Comment by phoqe** [comment]
Hello @MincePie! Glad you resolved the issue, I will take a look at it nonetheless!

**Comment by MincePie** [comment]
Thanks Linus.

I love this tool. You've done so much work!

Thank you.

**Comment by phoqe** [comment]
> Thanks Linus. I love this tool. You've done so much work! Thank you.
> […](#)

Thank you, Mel! :)
